{% set name = "dalex" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 061e2533d5783dd89d5a100c07238b866e55c6a7731e4ee4a564d7482a269d91

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools
    - pandas >=1.2.5
    - numpy >=1.20.3
    - scipy >=1.6.3
    - plotly >=5.1.0
    - tqdm >=4.61.2

test:
  requires:
    - lime >=0.2.0.1
    - scikit-learn >=0.22.0
    - statsmodels >=0.11.1
    - shap >=0.35.0
    - flask >=1.1.2
    - flask_cors >=3.0.8
    - requests >=2.24.0
    - python-kaleido >=0.2.1
    - ppscore >=1.2.0
    - ipywidgets >=7.6.3
  imports:
    - dalex
  source_files:
    - test
  commands: python -m unittest discover test

about:
  home: https://dalex.drwhy.ai/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Responsible Machine Learning in Python
  doc_url: https://dalex.drwhy.ai/python/
  dev_url: https://github.com/ModelOriented/DALEX/tree/master/python/dalex

extra:
  recipe-maintainers:
    - hbaniecki
